---
title: "Bioassay case study"
author: "Andrew Gelman and Aki Vehtari"
date: 2025-10-15
date-modified: today
date-format: iso
format:
  html:
    number-sections: true
    code-copy: true
    code-download: true
    code-tools: true
bibliography: ../casestudies.bib
---

This notebook includes the code for Bayesian Workflow book Section
3.5 *A simple example of probabilistic programming*.

## Introduction

We demonstrate the role of statistical programming environments and
probabilistic programming by going through the steps of data
analysis and computation in the context of a simple example.

We work through an example by @Racine-Grieve-Fluhler-etal:1986,
also included in Section 2.8 of Bayesian Data Analysis [@BDA3], of
a logistic regression fit to a bioassay experiment.

```{python}
#| label: setup
#| include: true
#| cache: false
import warnings
import sys
sys.path.insert(0, '..')

import arviz.preview as az
import bambi as bmb
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import xarray as xr
from scipy.special import expit


warnings.filterwarnings("ignore", category=FutureWarning)

az.style.use("arviz-variat")
az.rcParams["stats.ci_prob"] = 0.95
plt.rcParams["figure.dpi"] = 100
SEED = 7412
```


::: {.panel-tabset group="ppl"}
## CmdStanPy

```{python}
from cmdstanpy import CmdStanModel, disable_logging
disable_logging()
from utils import print_stan
```

## Numpyro
```{.python}
from jax import random
import jax.numpy as jnp
import numpyro
from  numpyro import distributions as dist
from numpyro.infer import NUTS, MCMC, Predictive

```
:::



## Bioassay data

Read the data from csv

```{python}
df_bioassay = pd.read_csv("data/bioassay.csv")
df_bioassay
```

Plot the data

```{python}
#| label: fig-bioassay-data-plot

fig, ax = plt.subplots(figsize=(7, 4))
ax.scatter(df_bioassay["dose"], df_bioassay["deaths"], s=60, color="black")
ax.set(xlabel="Dose log(g/ml)", ylabel="# of deaths")
ax.spines[["top", "right"]].set_visible(False)
```


::: {.panel-tabset group="ppl"}
## CmdStanPy
Data as list for CmdStanPy

```{python}
bioassay_data = {
    "J": len(df_bioassay),
    "x": df_bioassay["dose"].to_list(),
    "N": df_bioassay["batch_size"].to_list(),
    "y": df_bioassay["deaths"].to_list(),
}
```
## Numpyro
```{.python}
J = len(df_bioassay)
x = df_bioassay["dose"].values
N = df_bioassay["batch_size"].values
y = df_bioassay["deaths"].values
```
:::


## Stan models and inference

Model 0 (without priors).

::: {.panel-tabset group="ppl"}

Compile the Stan model code using pedantic mode

## CmdStanPy
```{python}
mod0 = CmdStanModel(
    stan_file=str("bioassay0.stan"),
    stanc_options={"warn-pedantic": True},
)
print_stan(mod0)
```

## Numpyro
```{.python}
def mod0(x, N, y=None):
    a = numpyro.sample("a", dist.Normal(0, 1e6)) # flat prior
    b = numpyro.sample("b", dist.Normal(0, 1e6)) # flat prior
    with numpyro.plate("J", len(N)):
        return numpyro.sample("y", dist.BinomialLogits(total_count=N, logits=a + b*x), obs=y)
```

:::

Model 1 (with priors). 

::: {.panel-tabset group="ppl"}

Compile the updated Stan model code using pedantic mode

## CmdStanPy
```{python}
mod1 = CmdStanModel(
    stan_file=str("bioassay1.stan"),
    stanc_options={"warn-pedantic": True},
)
print_stan(mod1)
mod1
```

## Numpyro
```{.python}
def mod1(x, N, y=None):
    a = numpyro.sample("a", dist.Normal(0, 5))
    b = numpyro.sample("b", dist.Normal(0, 5))
    with numpyro.plate("J", len(N)):
        return numpyro.sample("y", dist.BinomialLogits(total_count=N, logits=a + b*x), obs=y)
```
:::

Sample with default settings

::: {.panel-tabset group="ppl"}
## CmdStanPy

```{python}
#| label: fit1
#| results: hide
fit1 = mod1.sample(data=bioassay_data, seed=SEED, show_progress=False)
dt_bioassay1 = az.from_cmdstanpy(fit1)
```

## Numpyro
```{.python}
#| label: fit1
#| results: hide
kernel = NUTS(mod1)
mcmc = MCMC(kernel,  num_warmup=1000, num_samples=1000)
mcmc.run(random.PRNGKey(SEED), x=x, N=N, y=y)
dt_bioassay1 = az.from_numpyro(mcmc)
```
:::


## Posterior summary

Posterior summary and MCMC diagnostics

```{python}
az.summary(dt_bioassay1)
```

Plot 20 logistic curves given 20 posterior _draws_, and one logistic given the posterior mean

```{python}
# | label: fig-bioassay-posterior-plot
posterior = az.extract(dt_bioassay1, group="posterior")
posterior_20 = az.extract(dt_bioassay1, group="posterior", num_samples=20, random_seed=SEED)


_, ax = plt.subplots(figsize=(8, 3))
ax.scatter(
    df_bioassay["dose"],
    df_bioassay["deaths"] / df_bioassay["batch_size"],
    color="black",
)
ax.set(xlabel="Dose log(g/ml)", ylabel="Pr (death)")

xs = np.linspace(-1, 1, 200)
ax.plot(
    xs,
    expit(posterior_20["a"].values + posterior_20["b"].values * xs[:, None]),
    color="C1",
    lw=0.5,
    alpha=0.6,
)

ax.plot(
    xs,
    expit(posterior["a"].mean().item() + posterior["b"].mean().item() * xs),
    color="C0",
    lw=2,
)
```

## Derived quantities

Compute posterior draws for LD50 in log(g/ml) and in mg/ml

```{python}
ld50_log = -dt_bioassay1.posterior["a"] / dt_bioassay1.posterior["b"]
ld50_mg = 1000 * np.exp(ld50_log)
dt_bioassay1.posterior["LD50_log_g_ml"] = ld50_log
dt_bioassay1.posterior["LD50_mg_ml"] = ld50_mg
```

Summarise LD50 posterior

```{python}
az.summary(dt_bioassay1, var_names=["LD50_log_g_ml", "LD50_mg_ml"])
```

Quantile dot plot of the LD50 (mg/ml) posterior

```{python}
pc = az.plot_dist(
    dt_bioassay1,
    kind="dot",
    var_names="LD50_mg_ml",
    visuals={"point_estimate_text":False},
)
az.add_lines(pc, [500, 2000]);
```


Kernel density plot of the LD50 (mg/ml) posterior

```{python}
#| label: fig-bioassay-LD50-KDE

pc = az.plot_dist(
    dt_bioassay1,
    var_names="LD50_mg_ml",
    visuals={"point_estimate_text":False},
)
az.add_lines(pc, [500, 2000]);
```

## Bambi model and inference

The same model with `Bambi`

```{python}
model = bmb.Model(
    "prop(deaths, batch_size) ~ dose",
    data=df_bioassay,
    family="binomial",
    priors={
        "Intercept": bmb.Prior("Normal", mu=0, sigma=5),
        "dose": bmb.Prior("HalfNormal", sigma=8),
    },
)
idata_bambi = model.fit(random_seed=123)
```

Summary of the inference

```{python}
az.summary(idata_bambi)
```

With `bambi` we can use the built-in plotting functions in the interpret submodule.

```{python}
_, ax = bmb.interpret.plot_predictions(model, idata_bambi, "dose", use_hdi=False, fig_kwargs=dict(figsize=(10, 4)))
# Add data points
ax[0].scatter(
    df_bioassay["dose"],
    df_bioassay["deaths"] / df_bioassay["batch_size"],
    s=80,
    color="black",
)
# Tweak labels
ax[0].set(xlabel="Dose log(g/ml)", ylabel="Pr(death)")
```


## LD50 posterior

Compute posterior draws for lethal dose 50 (LD50) in log(g/ml) and in mg/ml

```{python}
ld50_bambi_log = -idata_bambi.posterior["Intercept"] / idata_bambi.posterior["dose"]
ld50_bambi_mg = 1000 * np.exp(ld50_bambi_log)
idata_bambi.posterior["LD50_log_g_ml"] = ld50_bambi_log
idata_bambi.posterior["LD50_mg_ml"] = ld50_bambi_mg
```

Posterior summary

```{python}
az.summary(idata_bambi, var_names=["LD50_log_g_ml", "LD50_mg_ml"])
```

Quantile dot plot of the LD50 (mg/ml) posterior.

```{python}
#| label: fig-bioassay-LD50-quantile-dots-bambi
pc = az.plot_dist(
    idata_bambi,
    kind="dot",
    var_names="LD50_mg_ml",
    visuals={"point_estimate_text":False},
)
az.add_lines(pc, [500, 2000]);
```

Kernel density plot of the LD50 (mg/ml) posterior.

```{python}
#| label: fig-bioassay-LD50-KDE-bambi

pc = az.plot_dist(
    idata_bambi,
    var_names="LD50_mg_ml",
    visuals={"point_estimate_text":False},
)
az.add_lines(pc, [500, 2000]);
```

## References {.unnumbered}

<div id="refs"></div>

## Licenses {.unnumbered}

* Code © 2025, Andrew Gelman and Aki Vehtari, licensed under BSD-3.
* Text © 2025, Andrew Gelman and Aki Vehtari, licensed under CC-BY-NC 4.0.
